
import java.awt.Color;
import java.awt.Dimension;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JSlider;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Famiglia Luisi
 */
public class UserInterface extends javax.swing.JFrame {

    int prova = 0;
    int tot = 0;
    //   int n = 0, p = 0;
    DefaultListModel Cart = new DefaultListModel();

    /**
     * Creates new form UserInterface
     */
    public UserInterface() {
        initComponents();
        

        //   lista.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        Menubutton = new javax.swing.JButton();
        Conferma = new javax.swing.JButton();
        seleziona = new javax.swing.JComboBox<>();
        Prodotti = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Carrello = new javax.swing.JLabel();
        tocart = new javax.swing.JButton();
        totale = new javax.swing.JLabel();
        successo = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        Delfromcart = new javax.swing.JButton();
        Quantita = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        jLabel1.setText("Interfaccia utente: prelevazione prodotto");

        Menubutton.setText("Menu principale");
        Menubutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenubuttonMouseClicked(evt);
            }
        });

        Conferma.setText("Conferma");
        Conferma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConfermaMouseClicked(evt);
            }
        });

        seleziona.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleziona categoria", "Alimentari", "Abbigliamento", "Elettronica" }));
        seleziona.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                selezionaItemStateChanged(evt);
            }
        });

        jLabel4.setText("Prodotto:");

        Carrello.setText("Il tuo carrello");
        Carrello.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        tocart.setText("Aggiungi al carrello");
        tocart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tocartMouseClicked(evt);
            }
        });

        totale.setText("Totale:");

        lista.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(lista);

        Delfromcart.setText("Rimuovi dal Carrello");
        Delfromcart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DelfromcartMouseClicked(evt);
            }
        });

        Quantita.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel2.setText("Quantità");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(successo, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(totale, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Conferma)
                                        .addGap(70, 70, 70)
                                        .addComponent(Menubutton))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(seleziona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tocart)
                                            .addComponent(Delfromcart, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jScrollPane4)
                                            .addComponent(Carrello, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(Prodotti, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Quantita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(30, 30, 30)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seleziona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Prodotti, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Carrello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71)
                                .addComponent(totale, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tocart)
                                .addGap(18, 18, 18)
                                .addComponent(Delfromcart)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(successo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Menubutton)
                            .addComponent(Conferma))
                        .addGap(34, 34, 34))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Quantita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenubuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenubuttonMouseClicked
        // TODO add your handling code here:
        Finestraprincipale.UserInterface.setVisible(false);
        ProvaFinestre.finestraprincipale.setVisible(true);

    }//GEN-LAST:event_MenubuttonMouseClicked

    private void ConfermaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConfermaMouseClicked
        // TODO add your handling code here:
        String item, item2;
        int cont = 0;
        for (int i = 0; i < Cart.getSize(); i++) {
            for (int j = i + 1; j < Cart.getSize(); j++) {
                item = (String) Cart.getElementAt(i);
                item2 = (String) (Cart.getElementAt(j));
                if (item.compareTo(item2) > 0) {
                    // test = (String) Cart.getElementAt(j);
                    Cart.setElementAt(item2, i);
                    Cart.setElementAt(item, j);

                }
            }
        }
        
        if (totale.getText().equals("Totale:")) {
            successo.setText("Devi selezionare qualcosa");
            successo.setForeground(Color.red);
        } else {
            System.out.println("Ecco a lei il suo scontrino:\nProdotto-Prezzo:");
            for (int i = 0; i < Cart.getSize(); i++) {
                item = (String) Cart.getElementAt(i);
                cont=0;
                  for (int h = i + 1; h < Cart.getSize(); h++) {
                    if (Cart.getElementAt(h).equals(Cart.getElementAt(h - 1))) {

                        cont++;
                    } else {
                        break;
                    }

                }
                  i = i + cont;
                  
                for (int j = 0; j < Finestra1.i; j++) {
                    if (Finestra1.vet[j].getDescrizione().equals(item)) {
                        if (Finestra1.vet[j].getQuantita() >= 0) {
                            Finestra1.vet[j].setQuantita(Finestra1.vet[j].getQuantita() - (cont+1));

                            System.out.println(Finestra1.vet[j].getDescrizione() + "  x" + (cont + 1) + "    " + Finestra1.vet[j].getPrezzo());
                            break;
                        } else {
                            System.out.println("il prodotto:" + Finestra1.vet[j].getDescrizione() + "non e'disponibile");
                        }
                    }

                }

            }
            Cart.removeAllElements();
            lista.setModel(Cart);
            System.out.println(totale.getText());
            tot = 0;
            totale.setText("Totale:");
            successo.setText("Ordine confermato");
            successo.setForeground(Color.green);

        }
    }//GEN-LAST:event_ConfermaMouseClicked

    private void selezionaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_selezionaItemStateChanged
        // TODO add your handling code here: 
        successo.setText("Creazione Ordine..");
        successo.setForeground(Color.black);
        Prodotti.removeAllItems();
        // Prodotti.addItem("Seleziona Prodotto");
        for (int i = 0; i < Finestra1.i; i++) {

            String test = (String) seleziona.getSelectedItem();
            if (test.equals(Finestra1.vet[i].getCategoria())) {
                Prodotti.addItem(Finestra1.vet[i].getDescrizione() + " Prezzo: " + Finestra1.vet[i].getPrezzo() + "€");

            }

        }
    }//GEN-LAST:event_selezionaItemStateChanged

    private void tocartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tocartMouseClicked
        // TODO add your handling code here:
        if (seleziona.getSelectedIndex() != 0) {
            String prod = (String) Prodotti.getSelectedItem();
            int x=(int)Quantita.getValue();
          
                    
            int p = 0;
            int n = 0;
            int i;
            for (i = 0; i < prod.length(); i++) {
                if (prod.charAt(i) == 32 && n == 0) {
                    n = i;
                } else if (prod.charAt(i) == 32 && p == 0) {
                    p = i;
                }
            }
            //  System.out.println("n:"+n+"p:"+p);
            int a=x;
            tot = tot+(( Integer.parseInt(prod.substring(p + 1, prod.length() - 1)))*a);
            prod = prod.substring(0, n);
           
            while(x!=0){
            Cart.addElement(prod);
            lista.setModel(Cart);
            
            x--;
            }
            totale.setText("Totale:" + tot + "€");
        }
    }//GEN-LAST:event_tocartMouseClicked

    private void DelfromcartMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DelfromcartMouseClicked
        // TODO add your handling code here:
        if (seleziona.getSelectedIndex() != 0) {
            String ogg = (String) Prodotti.getSelectedItem();
            int p = 0;
            int n = 0;
            int i;
            for (i = 0; i < ogg.length(); i++) {
                if (ogg.charAt(i) == 32 && n == 0) {
                    n = i;
                } else if (ogg.charAt(i) == 32 && p == 0) {
                    p = i;
                }
            }
            for (i = 0; i < Cart.getSize(); i++) {
                if (ogg.substring(0, n).equals(Cart.getElementAt(i))) {
                    Cart.removeElementAt(i);
                    tot = tot - Integer.parseInt(ogg.substring(p + 1, ogg.length() - 1));
            totale.setText("Totale:" + tot + "€");
            lista.setModel(Cart);
                    break;
                }
            }
            System.out.println(i);

        }
    }//GEN-LAST:event_DelfromcartMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Carrello;
    private javax.swing.JButton Conferma;
    private javax.swing.JButton Delfromcart;
    private javax.swing.JButton Menubutton;
    private javax.swing.JComboBox<String> Prodotti;
    private javax.swing.JSpinner Quantita;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JList<String> lista;
    private javax.swing.JComboBox<String> seleziona;
    private javax.swing.JLabel successo;
    private javax.swing.JButton tocart;
    private javax.swing.JLabel totale;
    // End of variables declaration//GEN-END:variables
}
